version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: serve -s dist
    container_name: frontend 
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend 
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
